name: .NET Core Build and Test

on:
  push:
    branches: 
      - develop
  pull_request:
    branches: 
      - release
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.101'
    - name: Install dependencies
      run: dotnet restore src
      with:
        dotnet-version: '2.2.101'
    - name: Build
      run: dotnet build src --configuration Release --no-restore
      with:
        dotnet-version: '2.2.101'
    - name: Test
      run: dotnet test tests --verbosity normal
      with:
        dotnet-version: '2.2.101'
